export const actions = {
    ADDCHILD: 'ADDCHILD',
    ADDEVENT: 'ADDEVENT',
    ADDPARENT: 'ADDPARENT',
    ADDSUPERVISOR: 'ADDSUPERVISOR',
    ADDCONFIRM: 'ADDCONFIRM',
    REMOVEPARENTSIGN: 'REMOVEPARENTSIGN',
    REMOVESUPERVISORSIGN: 'REMOVESUPERVISORSIGN',
    ADDBOARD: 'ADDBOARD'
};
